export type CityTier = 1 | 2 | 3 | 4;

export interface City {
  name: string;
  slug: string;
  state: string;
  tier: CityTier;
  description?: string; // optional unique local hook
}

function toSlug(name: string): string {
  return name.toLowerCase().replace(/[\s\/]+/g, "-").replace(/[^a-z0-9-]/g, "");
}

const rawCities: Array<[string, string, CityTier]> = [
  // Tier 1 — Metro (8)
  ["Pune", "Maharashtra", 1],
  ["Mumbai", "Maharashtra", 1],
  ["Delhi", "Delhi", 1],
  ["Bengaluru", "Karnataka", 1],
  ["Hyderabad", "Telangana", 1],
  ["Chennai", "Tamil Nadu", 1],
  ["Kolkata", "West Bengal", 1],
  ["Ahmedabad", "Gujarat", 1],

  // Tier 2 — Large Cities (42+)
  ["Navi Mumbai", "Maharashtra", 2],
  ["Thane", "Maharashtra", 2],
  ["Pimpri-Chinchwad", "Maharashtra", 2],
  ["Nashik", "Maharashtra", 2],
  ["Nagpur", "Maharashtra", 2],
  ["Surat", "Gujarat", 2],
  ["Vadodara", "Gujarat", 2],
  ["Rajkot", "Gujarat", 2],
  ["Lucknow", "Uttar Pradesh", 2],
  ["Kanpur", "Uttar Pradesh", 2],
  ["Agra", "Uttar Pradesh", 2],
  ["Meerut", "Uttar Pradesh", 2],
  ["Ghaziabad", "Uttar Pradesh", 2],
  ["Noida", "Uttar Pradesh", 2],
  ["Gurgaon", "Haryana", 2],
  ["Faridabad", "Haryana", 2],
  ["Jaipur", "Rajasthan", 2],
  ["Jodhpur", "Rajasthan", 2],
  ["Kota", "Rajasthan", 2],
  ["Indore", "Madhya Pradesh", 2],
  ["Bhopal", "Madhya Pradesh", 2],
  ["Patna", "Bihar", 2],
  ["Ranchi", "Jharkhand", 2],
  ["Jamshedpur", "Jharkhand", 2],
  ["Raipur", "Chhattisgarh", 2],
  ["Bhubaneswar", "Odisha", 2],
  ["Visakhapatnam", "Andhra Pradesh", 2],
  ["Vijayawada", "Andhra Pradesh", 2],
  ["Coimbatore", "Tamil Nadu", 2],
  ["Madurai", "Tamil Nadu", 2],
  ["Tiruchirappalli", "Tamil Nadu", 2],
  ["Ludhiana", "Punjab", 2],
  ["Amritsar", "Punjab", 2],
  ["Jalandhar", "Punjab", 2],
  ["Chandigarh", "Punjab", 2],
  ["Allahabad", "Uttar Pradesh", 2],
  ["Varanasi", "Uttar Pradesh", 2],
  ["Aurangabad", "Maharashtra", 2],
  ["Solapur", "Maharashtra", 2],
  ["Howrah", "West Bengal", 2],
  ["Asansol", "West Bengal", 2],
  ["Durgapur", "West Bengal", 2],
  ["Siliguri", "West Bengal", 2],
  ["Guwahati", "Assam", 2],

  // Tier 3 — Mid Cities (80+)
  ["Kolhapur", "Maharashtra", 3],
  ["Sangli", "Maharashtra", 3],
  ["Satara", "Maharashtra", 3],
  ["Ahmednagar", "Maharashtra", 3],
  ["Latur", "Maharashtra", 3],
  ["Jalgaon", "Maharashtra", 3],
  ["Dhule", "Maharashtra", 3],
  ["Amravati", "Maharashtra", 3],
  ["Chandrapur", "Maharashtra", 3],
  ["Akola", "Maharashtra", 3],
  ["Nandurbar", "Maharashtra", 3],
  ["Washim", "Maharashtra", 3],
  ["Hingoli", "Maharashtra", 3],
  ["Parbhani", "Maharashtra", 3],
  ["Beed", "Maharashtra", 3],
  ["Bhandara", "Maharashtra", 3],
  ["Gadchiroli", "Maharashtra", 3],
  ["Gondia", "Maharashtra", 3],
  ["Wardha", "Maharashtra", 3],
  ["Yavatmal", "Maharashtra", 3],
  ["Ratnagiri", "Maharashtra", 3],
  ["Sindhudurg", "Maharashtra", 3],
  ["Raigad", "Maharashtra", 3],
  ["Ulhasnagar", "Maharashtra", 3],
  ["Bhiwandi", "Maharashtra", 3],
  ["Mira-Bhayandar", "Maharashtra", 3],
  ["Vasai-Virar", "Maharashtra", 3],
  ["Panvel", "Maharashtra", 3],
  ["Lonavala", "Maharashtra", 3],
  ["Alibaug", "Maharashtra", 3],
  ["Mysuru", "Karnataka", 3],
  ["Mangaluru", "Karnataka", 3],
  ["Hubballi", "Karnataka", 3],
  ["Dharwad", "Karnataka", 3],
  ["Belgaum", "Karnataka", 3],
  ["Tumkur", "Karnataka", 3],
  ["Davangere", "Karnataka", 3],
  ["Raichur", "Karnataka", 3],
  ["Bidar", "Karnataka", 3],
  ["Gulbarga", "Karnataka", 3],
  ["Hassan", "Karnataka", 3],
  ["Udupi", "Karnataka", 3],
  ["Manipal", "Karnataka", 3],
  ["Kolar", "Karnataka", 3],
  ["Chikballapur", "Karnataka", 3],
  ["Chikmagalur", "Karnataka", 3],
  ["Shimoga", "Karnataka", 3],
  ["Ballari", "Karnataka", 3],
  ["Warangal", "Telangana", 3],
  ["Khammam", "Telangana", 3],
  ["Nizamabad", "Telangana", 3],
  ["Karimnagar", "Telangana", 3],
  ["Rajahmundry", "Andhra Pradesh", 3],
  ["Nellore", "Andhra Pradesh", 3],
  ["Kurnool", "Andhra Pradesh", 3],
  ["Anantapur", "Andhra Pradesh", 3],
  ["Guntur", "Andhra Pradesh", 3],
  ["Tirupati", "Andhra Pradesh", 3],
  ["Kadapa", "Andhra Pradesh", 3],
  ["Ongole", "Andhra Pradesh", 3],
  ["Salem", "Tamil Nadu", 3],
  ["Tiruppur", "Tamil Nadu", 3],
  ["Erode", "Tamil Nadu", 3],
  ["Thanjavur", "Tamil Nadu", 3],
  ["Dindigul", "Tamil Nadu", 3],
  ["Cuddalore", "Tamil Nadu", 3],
  ["Vellore", "Tamil Nadu", 3],
  ["Tirunelveli", "Tamil Nadu", 3],
  ["Thoothukudi", "Tamil Nadu", 3],
  ["Chengalpattu", "Tamil Nadu", 3],
  ["Kanchipuram", "Tamil Nadu", 3],
  ["Kochi", "Kerala", 3],
  ["Thrissur", "Kerala", 3],
  ["Kozhikode", "Kerala", 3],
  ["Dehradun", "Uttarakhand", 3],
  ["Srinagar", "Jammu & Kashmir", 3],
  ["Jammu", "Jammu & Kashmir", 3],
  ["Shimla", "Himachal Pradesh", 3],
  ["Bikaner", "Rajasthan", 3],
  ["Udaipur", "Rajasthan", 3],
  ["Ajmer", "Rajasthan", 3],
  ["Jabalpur", "Madhya Pradesh", 3],
  ["Gwalior", "Madhya Pradesh", 3],
  ["Bhilai", "Chhattisgarh", 3],
  ["Bilaspur", "Chhattisgarh", 3],
  ["Cuttack", "Odisha", 3],
  ["Rourkela", "Odisha", 3],
  ["Sambalpur", "Odisha", 3],
  ["Jamnagar", "Gujarat", 3],
  ["Junagadh", "Gujarat", 3],
  ["Gandhinagar", "Gujarat", 3],
  ["Anand", "Gujarat", 3],
  ["Bhavnagar", "Gujarat", 3],
  ["Morbi", "Gujarat", 3],

  // Tier 4 — Emerging Cities (70+)
  ["Puducherry", "Puducherry", 4],
  ["Panaji", "Goa", 4],
  ["Margao", "Goa", 4],
  ["Gangtok", "Sikkim", 4],
  ["Shillong", "Meghalaya", 4],
  ["Itanagar", "Arunachal Pradesh", 4],
  ["Dispur", "Assam", 4],
  ["Silvassa", "Dadra & Nagar Haveli", 4],
  ["Daman", "Daman & Diu", 4],
  ["Diu", "Daman & Diu", 4],
  ["Vapi", "Gujarat", 4],
  ["Veraval", "Gujarat", 4],
  ["Porbandar", "Gujarat", 4],
  ["Botad", "Gujarat", 4],
  ["Chhota Udaipur", "Gujarat", 4],
  ["Mehsana", "Gujarat", 4],
  ["Nadiad", "Gujarat", 4],
  ["Godhra", "Gujarat", 4],
  ["Narasaraopet", "Andhra Pradesh", 4],
  ["Chittoor", "Andhra Pradesh", 4],
  ["Srikakulam", "Andhra Pradesh", 4],
  ["Eluru", "Andhra Pradesh", 4],
  ["Tenali", "Andhra Pradesh", 4],
  ["Adoni", "Andhra Pradesh", 4],
  ["Hindupur", "Andhra Pradesh", 4],
  ["Tadipatri", "Andhra Pradesh", 4],
  ["Vikarabad", "Telangana", 4],
  ["Malappuram", "Kerala", 4],
  ["Kannur", "Kerala", 4],
  ["Kasaragod", "Kerala", 4],
  ["Kollam", "Kerala", 4],
  ["Kottayam", "Kerala", 4],
  ["Palakkad", "Kerala", 4],
  ["Alappuzha", "Kerala", 4],
  ["Idukki", "Kerala", 4],
  ["Nagapattinam", "Tamil Nadu", 4],
  ["Sivakasi", "Tamil Nadu", 4],
  ["Ratnagiri", "Maharashtra", 4],
  ["Osmanabad", "Maharashtra", 4],
  ["Nainital", "Uttarakhand", 4],
  ["Rishikesh", "Uttarakhand", 4],
  ["Mussoorie", "Uttarakhand", 4],
  ["Patiala", "Punjab", 4],
  ["Bathinda", "Punjab", 4],
  ["Rohtak", "Haryana", 4],
  ["Panihati", "West Bengal", 4],
  ["Muzaffarpur", "Bihar", 4],
  ["Patna", "Bihar", 4],
  ["Bhagalpur", "Bihar", 4],
  ["Latur", "Maharashtra", 4],
  ["Nanded", "Maharashtra", 4],
  ["Kakinada", "Andhra Pradesh", 4],
  ["Mandya", "Karnataka", 4],
  ["Hospet", "Karnataka", 4],
  ["Kodagu", "Karnataka", 4],
  ["Jhansi", "Uttar Pradesh", 4],
  ["Bareilly", "Uttar Pradesh", 4],
  ["Moradabad", "Uttar Pradesh", 4],
  ["Aligarh", "Uttar Pradesh", 4],
  ["Gorakhpur", "Uttar Pradesh", 4],
  ["Saharanpur", "Uttar Pradesh", 4],
  ["Muzaffarnagar", "Uttar Pradesh", 4],
  ["Rampur", "Uttar Pradesh", 4],
  ["Loni", "Uttar Pradesh", 4],
  ["Firozabad", "Uttar Pradesh", 4],
  ["Dhanbad", "Jharkhand", 4],
  ["Bokaro", "Jharkhand", 4],
  ["Ajmer", "Rajasthan", 4],
  ["Imphal", "Manipur", 4],
  ["Aizawl", "Mizoram", 4],
  ["Kohima", "Nagaland", 4],
  ["Agartala", "Tripura", 4],
];

export const CITIES: City[] = rawCities.map(([name, state, tier]) => ({
  name,
  slug: toSlug(name),
  state,
  tier,
}));

export const CITY_MAP: Record<string, City> = Object.fromEntries(
  CITIES.map(c => [c.slug, c])
);

export function getCityBySlug(slug: string): City | undefined {
  return CITY_MAP[slug];
}

export function generateCityStaticParams() {
  return CITIES.map(c => ({ city: c.slug }));
}

// Group cities by state for footer display
export function getCitiesByState(): Record<string, City[]> {
  const map: Record<string, City[]> = {};
  for (const city of CITIES) {
    if (!map[city.state]) map[city.state] = [];
    map[city.state].push(city);
  }
  return map;
}

// Key states for featured city sections
export const FEATURED_STATES = [
  "Maharashtra",
  "Gujarat",
  "Karnataka",
  "Tamil Nadu",
  "Telangana",
  "Andhra Pradesh",
  "Kerala",
  "Delhi",
  "Uttar Pradesh",
  "Rajasthan",
];
